### ISSUE TITLE
不错啊，可是你为毛把bin目录也给传上去了呢

### ISSUE THREAD

**Issue by duguying** [raojun/BookManage#1]
不错啊，可是你为毛把bin目录也给传上去了呢:confuse:

**Comment by raojun** [comment]
懒呗！ 哈哈------------------ 原始邮件 ------------------
发件人: "Rex Lee(李俊)"notifications@github.com
发送时间: 2013年12月2日(星期一) 晚上8:58
收件人: "raojun/BookManage"BookManage@noreply.github.com;
主题: [BookManage] 不错啊，可是你为毛把bin目录也给传上去了呢 (#1)

不错啊，可是你为毛把bin目录也给传上去了呢:confuse:

&mdash;
